Ability to run Temporal Query
spatie/laravel-event-sourcing pull request #187
Opened 2020-12-30 03:03 UTC by dilab

as discussed in this: https://github.com/spatie/laravel-event-sourcing/issues/178

2020-12-30 16:09 UTC, freekmurze requested changes

2020-12-30 16:09 UTC, freekmurze commented on .idea/laravel-event-sourcing.iml
> +<?xml version="1.0" encoding="UTF-8"?>
Please remove the `.idea` directory from this PR.

It might be helpful to create a global gitgnore to avoid future problems.

2020-12-30 16:09 UTC, freekmurze commented on docs/advanced-usage/temporal-query.md
> +One feature of ES is able to perform a temporal query quoted by Martin Fowler:
Instead of using a quote, tell in simple words what a temporal query is.

2020-12-30 16:09 UTC, freekmurze commented on src/AggregateRoots/AggregateRoot.php
> +    public static function retrieveUntil(string $uuid, \DateTimeImmutable $tillDateTime)
Use the `self` type hint, remove the docblock, and import all namespaces so that `\` can be removed.

2020-12-31 01:43 UTC, dilab commented
@freekmurze updated as requested

2021-01-04 07:34 UTC, freekmurze commented
The `.idea` files are still present in this PR: https://github.com/spatie/laravel-event-sourcing/pull/187/files

2021-01-04 07:50 UTC, dilab commented
@freekmurze removed completely.

2021-01-12 00:48 UTC, dilab commented
@freekmurze how is the PR review going?

2021-01-12 00:56 UTC, freekmurze commented
Focusing a bit on other things atm, but I'll swing back to this when I have some time!

2021-01-19 18:37 UTC, morrislaptop commented
Is this a duplicate of #182 ?

2021-01-27 05:55 UTC, brendt commented
Thanks, the concept is now called `EventQuery` and already implemented in the v5 branch

2021-01-27 05:55 UTC, closed without merging