Added an extra rejection to prevent events being passed to invalid handlers
spatie/laravel-event-sourcing pull request #438
Opened 2023-09-01 10:00 UTC by 27pchrisl

Fixes #437. Essentially if you'll accept null you're too accepting (un-typed params, variadics etc.)

2023-09-04 09:19 UTC, sebastiandedeyne requested changes

2023-09-04 09:19 UTC, sebastiandedeyne commented on src/AggregateRoots/AggregateRoot.php
> +            ->reject(fn (Method $method) => $method->accepts(null))
Very elegant fix!

2023-09-04 09:20 UTC, sebastiandedeyne requested changes
Can we do this in `HandlesEvents` too to keep the logic between discovering handlers for aggregate roots & projectors/reactors consistent?

Or could that be a breaking change for some?

2023-09-04 09:41 UTC, 27pchrisl commented
I can't think of a reason someone would have deliberately created a real event handler that could accept null as its first argument, or even done that accidentally....

2023-09-05 04:52 UTC, sebastiandedeyne commented
The only case I can think of is a "catch-all" projector or reactor without a typehint, but in that case it can be fixed by hinting `ShouldBeStored`.

Merging and tagging, thank you!

2023-09-05 04:52 UTC, merged